#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

. /warewulf/transports/http/functions

HTTP=${WWHTTP:-http}

echo "== wwgetnodeconfig ==" >> /var/log/warewulf/provision/http.log
while true; do
    for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do
        if curl --fail --local-port 100-1023 -s "$HTTP://$master/WW/nodeconfig?hwaddr=$WWINIT_HWADDR" 2>>/var/log/warewulf/provision/http.log; then
            exit 0
        fi
    done
    echo -n "." 1>&2
    throttled_sleep
done
