#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

if [ -n "$SET_X" ]; then
    set -x
fi

. /warewulf/transports/http/functions

TMPFILE=`mktemp`

cd ${NEWROOT:-/}

while true; do
    for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do

        rm -f /tmp/vnfs-download 2>/dev/null
        if ! mkfifo /tmp/vnfs-download 2>/dev/null; then
            echo "ERROR: Could not create the fifo!"
            exit 1
        fi

        gunzip < /tmp/vnfs-download | bsdtar -pxf - &
        EXTRACT_PID=$!

        wget -q -O /tmp/vnfs-download http://$master/WW/vnfs?hwaddr=$WWINIT_HWADDR >/dev/null 2>&1
        WGETEXIT=$?

        if [ "${WGETEXIT}" -ne 0 ]; then
          kill "${EXTRACT_PID}"
          continue
        else 
          wait "${EXTRACT_PID}"
        fi

        if [ -x "$NEWROOT/sbin/init" -o -h "$NEWROOT/sbin/init" ]; then
            exit 0
	      fi

    done
    echo -n "."
    throttled_sleep
done

exit 1
