#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


> /etc/network.conf

if test -n "$ip"; then
   ip address add $ip/$subnet broadcast + dev $interface
   echo "IPADDR=$ip" >> /etc/network.conf
   echo "NETMASK=$subnet" >> /etc/network.conf
fi
if test -n "$dns"; then
   > /etc/resolv.conf
   for i in "$dns"; do
      echo "nameserver $i" >> /etc/resolv.conf
   done
fi
if test -n "$router"; then
   ip route add default via $router
   echo "GATEWAY=$router" >> /etc/network.conf
fi
if test -n "$hostname"; then
    hostname $hostname
    echo "HOSTNAME=$hostname" >> /etc/network.conf
fi
if test -n "$serverid"; then
    echo "DHCP_SERVER=$serverid" >> /etc/network.conf
fi
