#!/bin/sh
#
# Copyright (c) 2003-2021, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

if [ -n "$SET_X" ]; then
    set -x
fi

WWHTTP=${WWHTTP:-https}

. /warewulf/transports/http/wwgetnodeconfig
