#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2017, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

[ -f /etc/functions ] && . /etc/functions

SET_X=1
export SET_X

cd "${NEWROOT}"

# Status for parent
wwrunning

wwgetvnfs

RC=$?

msg_white " * getvnfs"  

if [ ${RC} -ne 0 ]; then
    exit 255
fi

