#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

if [ -d "${NEWROOT}/etc/sysconfig/network-scripts" ]; then
    cp -f /tmp/ifcfg-* "${NEWROOT}/etc/sysconfig/network-scripts/"
elif [ -d "${NEWROOT}/etc/network" ]; then
    cp -f /tmp/interfaces "${NEWROOT}/etc/network/"
fi

if [ -n "$HOSTNAME" ]; then
    if [ -f "${NEWROOT}/usr/bin/hostnamectl" ] || [ -f "${NEWROOT}/etc/debian_version" ]; then
        echo "$HOSTNAME" > "${NEWROOT}/etc/hostname"
    elif [ -f "${NEWROOT}/etc/sysconfig/network" ]; then
        sed -i '/^HOSTNAME.*$/d' "${NEWROOT}/etc/sysconfig/network"
        echo "HOSTNAME=${HOSTNAME}" >> "${NEWROOT}/etc/sysconfig/network"
    fi
fi

if [ -z "${WWNOFSTABUPDATE}" ]; then
    if [ -f "${NEWROOT}/etc/fstab" ]; then
        > "${NEWROOT}/etc/fstab_"
        while read i; do
            if [ "${i}" = "#GENERATED_ENTRIES#" ]; then
                cat /tmp/fstab >> "${NEWROOT}/etc/fstab_"
            else
                echo "${i}" >> "${NEWROOT}/etc/fstab_"
            fi

        done < "${NEWROOT}/etc/fstab"

        cp -f "${NEWROOT}/etc/fstab_" "${NEWROOT}/etc/fstab"
        rm -f "${NEWROOT}/etc/fstab_"
    else
        cp -f /tmp/fstab "${NEWROOT}/etc/fstab"
    fi
fi

