#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2017, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

if [ ! -d "${NEWROOT}/dev" ]; then
    mkdir -m 0755 -p "${NEWROOT}/dev";
fi

if ! mount -t devtmpfs devtmpfs "${NEWROOT}/dev" >/dev/null 2>&1; then
    cp -rap /dev/* "${NEWROOT}/dev/"
fi

