#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2017, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

if [ -n "${WWNOKMODCOPY}" ]; then
    # Skipping
    exit 1
fi

KVERSION=$(uname -r)

if [ -d "/lib/modules/${KVERSION}" ]; then
    if [ ! -d "${NEWROOT}/lib/modules/${KVERSION}" ]; then
        mkdir -p "${NEWROOT}/lib/modules/${KVERSION}"
    fi
    cp -r /lib/modules/"${KVERSION}"/* "${NEWROOT}/lib/modules/${KVERSION}/"
fi

if [ -d "/lib/firmware/${KVERSION}" ]; then
    if [ ! -d "${NEWROOT}/lib/firmware/${KVERSION}" ]; then
        mkdir -p "${NEWROOT}/lib/firmware/${KVERSION}"
    fi
    cp -r /lib/firmware/"${KVERSION}"/* "${NEWROOT}/lib/firmware/${KVERSION}/"
fi

DEPMOD="$(chroot "${NEWROOT}" /bin/readlink -f /sbin/depmod)"
if [ -x "${NEWROOT}${DEPMOD}" ]; then
    chroot "${NEWROOT}" /sbin/depmod -a
fi

if [ -e "${NEWROOT}"/lib/modules/"${KVERSION}"/sysctl.conf -a ! -e "${NEWROOT}"/boot/sysctl.conf-"${KVERSION}" ]; then
    ln -s /lib/modules/"${KVERSION}"/sysctl.conf" "${NEWROOT}"/boot/sysctl.conf-"${KVERSION}"
fi

exit 0
