#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

SKIP_MTAB=1

if [ ! -d "${NEWROOT}/dev/shm" ]; then
    install -d -m 1777 "${NEWROOT}/dev/shm"
fi

# Newer distributions symlink to /proc/self/mounts, so don't populate mtab
# if mtab is a symlink.
if [ ! -h "${NEWROOT}/etc/mtab" ]; then
    > "${NEWROOT}/etc/mtab"
    SKIP_MTAB=0
fi

# Loop over any mounts to or under NEWROOT
/usr/bin/awk -v NEWROOT="^${NEWROOT}" '$2 ~ NEWROOT {print}' /etc/mtab | sort -k 2 -r | while read dev mp type opts freq pass; do
    if [ "${mp}" = "${NEWROOT}" ]; then
      if [ "${SKIP_MTAB}" -eq 0 ]; then
        echo "$dev / $type $opts $freq $pass" > "${NEWROOT}/etc/mtab"
      fi
    else
        if ! umount "${mp}"; then
            mount -o remount,ro "${mp}"
        fi
    fi
done

